kind: Service
apiVersion: v1
metadata:
  name: service-nodeport-web

spec:
 
  type: NodePort 
  selector:
    app: web 

  ports:
    - protocol: TCP
      nodePort: 30008   
      port: 8080
      targetPort: 8080 

  
