apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume.yml
  #labels:
   # app: web
spec:
  containers:
  - name: mysql
    image: mysql
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
   # ports:
   # - containerPort: 8080


    env:
    - name: MYSQL_ROOT_PASSWORD
      value: PASSWORD
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    - name: MYSQL_DATABASE
      value: eazytraining
  volumes:
  - name: mysql-data
    hostPath:
      path: /data-volume
    #  type: Directory
